services:
  cmake:
    build: 
      context: .
      dockerfile: Dockerfile.windows
    container_name: cmake
    image: cmake-image
    volumes:
      - ./app:c:/app
    environment:
      - CMAKE_PROJECT_NAME=minimal-cmake-example
    # fix for docker compose windows container bug
    networks:
      - default_net

# fix for docker compose windows container bug
networks:
  default_net:
    external: true
    name: nat